services:
  easyapplyapp:
    build: .
    container_name: easyapplyapp
    restart: always
    environment:
      - OPEN_API_KEY=value
    expose:
      - 8000

  nginx:
   build: ./nginx
   restart: always
   ports:
    - "80:80"